-- ================================================================
-- EJECUTA ESTO EN SUPABASE → SQL Editor
-- Corrije el error: "cannot insert a non-DEFAULT value into column año_registro_sistema"
-- ================================================================

-- 1. Ver los triggers que tiene la tabla (copia el nombre que aparezca)
SELECT tgname AS trigger_name
FROM pg_trigger t
JOIN pg_class c ON c.oid = t.tgrelid
WHERE c.relname = 'envios_ventas'
  AND NOT t.tgisinternal;

-- 2. Eliminar TODOS los triggers conflictivos de la tabla de una vez
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT tgname
    FROM pg_trigger t
    JOIN pg_class c ON c.oid = t.tgrelid
    WHERE c.relname = 'envios_ventas'
      AND NOT t.tgisinternal
  LOOP
    EXECUTE 'DROP TRIGGER IF EXISTS ' || quote_ident(r.tgname) || ' ON public.envios_ventas';
    RAISE NOTICE 'Trigger eliminado: %', r.tgname;
  END LOOP;
END;
$$;

-- 3. Verificar que ya no hay triggers
SELECT tgname FROM pg_trigger t
JOIN pg_class c ON c.oid = t.tgrelid
WHERE c.relname = 'envios_ventas' AND NOT t.tgisinternal;
-- Si no devuelve filas → OK, problema resuelto.

-- ================================================================
-- Si el error PERSISTE después de eliminar los triggers,
-- ejecuta esto adicionalmente:
-- ================================================================
-- ALTER TABLE public.envios_ventas
--   ALTER COLUMN año_registro_sistema     SET GENERATED BY DEFAULT,
--   ALTER COLUMN mes_registro_sistema     SET GENERATED BY DEFAULT,
--   ALTER COLUMN dia_num_registro_sistema SET GENERATED BY DEFAULT,
--   ALTER COLUMN dia_abc_registro_sistema SET GENERATED BY DEFAULT;
