-- ============================================================================
-- ⚠️ OBSOLETO — NO EJECUTAR.
--
-- Esta migración se creó para permitir REFRESH MATERIALIZED VIEW CONCURRENTLY
-- desde el botón "Forzar Refresh". Se DESCARTÓ esa estrategia porque refrescar
-- la MV bajo demanda es pesado y sobrecarga la BD (por eso su cron ya está
-- desactivado en server.js).
--
-- El botón "Forzar Refresh" ahora es LIVIANO: solo limpia el caché en memoria
-- del servidor (no toca la MV). Ver forceRefreshVelsa() en
-- indicadoresVelsaMaterialized.controller.js.
--
-- No se necesita ningún índice único ni recrear la MV. Puedes borrar este
-- archivo con tranquilidad.
-- ============================================================================
